name: example
description: Example app demonstrating statemanagement library
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  super_qubit:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0

flutter:
  uses-material-design: true
