name: super_qubit
description: A hierarchical state management library for Flutter with SuperQubit and Qubit support.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  test: ^1.25.6
  mocktail: ^1.0.4

